version: '3'

vars:
  PORT:
    sh: ls /dev/ttyACM* /dev/ttyUSB* /dev/tty.usb* 2>/dev/null | head -n1

tasks:
  require-decoder:
    internal: true
    preconditions:
      - sh: ls "{{.PORT}}"
        msg: Decoder device not connected (physically connect the MAX78000 to your computer over USB and run the command again)
    cmds:
      - '[ "$(stat -c %a {{.PORT}})" != "777" ] && sudo chmod 777 {{.PORT}} || true'

  docs:
    desc: Build documentation design file into PDF and SVG artifacts
    dir: docs
    cmds:
      - typstyle -i design.typ
      - typst compile design.typ
      - typst compile design.typ pages/page-{p}.svg

  1-gen-secrets:
    desc: Generate secrets
    vars:
      CHANNELS: '{{.CLI_ARGS | default "1 2 3"}}'
    cmds:
      - python -m ectf25_design.gen_secrets -f global.secrets {{.CHANNELS}}

  2-build-firmware:
    desc: Build the firmware image
    vars:
      DECODER_ID: '{{.DECODER_ID | default "0xdeadbeef"}}'
    cmds:
      - docker build -t decoder decoder
      - docker run --rm -v ./decoder/:/decoder -v ./global.secrets:/global.secrets:ro -v ./deadbeef_build:/out -e DECODER_ID={{.DECODER_ID}} decoder

  3-flash:
    desc: Flash the built firmware image onto the Decoder
    deps:
      - task: require-decoder
    cmds:
      - python -m ectf25.utils.flash ./deadbeef_build/max78000.bin {{.PORT}}

  4-gen-subscription:
    desc: Generate a subscription
    vars:
      FILE: '{{.FILE | default "subscription.bin"}}'
      DEVICE_ID: '{{.DEVICE_ID | default "0xDEADBEEF"}}'
      START: '{{.START | default "0"}}'
      END: '{{.END | default "128"}}'
      CHANNEL: '{{.CHANNEL | default "1"}}'
    cmds:
      - python -m ectf25_design.gen_subscription -f global.secrets {{.FILE}} {{.DEVICE_ID}} {{.START}} {{.END}} {{.CHANNEL}}

  5-subscribe:
    desc: Take a subscription file and send it to the Decoder
    deps:
      - task: require-decoder
    vars:
      FILE: '{{.FILE | default "subscription.bin"}}'
    preconditions:
      - sh: ls {{.FILE}}
        msg: Subscription '{{.FILE}}' does not exist
    cmds:
      - python -m ectf25.tv.subscribe {{.FILE}} {{.PORT}}

  6-list:
    desc: Asks the Decoder to list the subscriptions that it currently has
    deps:
      - task: require-decoder
    cmds:
      - python -m ectf25.tv.list {{.PORT}}

  7-uplink:
    desc: Encodes sample frames with the custom encoder function and sends them to the satellite
    prefix: uplink
    cmds:
      - python -m ectf25.uplink global.secrets localhost 2000 1:10:frames/x_c0.json

  8-satellite:
    desc: Broadcasts all frames received from the uplink to all listening TVs on the host computer
    prefix: satellite
    cmds:
      - python -m ectf25.satellite localhost 2000 localhost 1:2001

  delayed-satellite:
    internal: true
    cmds:
      - sleep 2
      - task: satellite

  9-tv:
    desc: Receives encoded frames from the satellite and decodes with a Decoder connected to the host computer
    deps:
      - task: require-decoder
    cmds:
      - python -m ectf25.tv.run localhost 2001 {{.PORT}}

  10-end-to-end:
    desc: Run a complete end to end test
    deps:
      - task: uplink
      - task: delayed-satellite

  bench-encoder:
    desc: Benchmark the encoder
    cmds:
      - python benches/encoder.py

  bench-decoder:
    desc: Benchmark the decoder
    deps:
      - task: require-decoder
    cmds:
      - python benches/decoder.py {{.PORT}}

  bench-subscription:
    desc: Benchmark creating a subscription on the decoder
    deps:
      - task: require-decoder
    cmds:
      - python benches/subscription.py {{.PORT}}

  stress-encoder:
    desc: Use MITRE's stress test to benchmark the encoder
    generates:
      - frames/custom.json
    cmds:
      - python -m ectf25.utils.stress_test -t 6400 encode global.secrets --dump frames/custom.json

  stress-decoder:
    desc: Use MITRE's stress test to benchmark the decoder
    deps:
      - task: require-decoder
      - task: stress-encoder
    cmds:
      - task: 4-gen-subscription
        vars:
          END: 18446744073709551615
          CHANNEL: 1
      - task: 5-subscribe
      - task: 4-gen-subscription
        vars:
          END: 18446744073709551615
          CHANNEL: 2
      - task: 5-subscribe
      - task: 4-gen-subscription
        vars:
          END: 18446744073709551615
          CHANNEL: 3
      - task: 5-subscribe
      - task: 6-list
      - python -m ectf25.utils.stress_test -t 6400 decode {{.PORT}} frames/custom.json
