"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import struct
import json
from blake3 import blake3
from Crypto.Cipher import Salsa20
from Crypto.Signature import eddsa
from Crypto.PublicKey import ECC

HASH_TREE_HEIGHT = 64
LEFT_SALT = b"L"
RIGHT_SALT = b"R"


class Encoder:
    seeds: dict[int, bytes]
    signer: eddsa.EdDSASigScheme
    metadata_key: bytes

    def __init__(self, secrets: bytes):
        """
        You **may not** change the arguments or returns of this function!

        :param secrets: Contents of the secrets file generated by
            ectf25_design.gen_secrets
        """

        secrets = json.loads(secrets)
        self.seeds = secrets["seeds"]
        self.signer = eddsa.new(ECC.import_key(secrets["private_key"]), "rfc8032")
        self.metadata_key = bytes.fromhex(secrets["metadata_key"])

    def encode(self, channel: int, frame: bytes, timestamp: int) -> bytes:
        """The frame encoder function

        This will be called for every frame that needs to be encoded before being
        transmitted by the satellite to all listening TVs

        You **may not** change the arguments or returns of this function!

        :param channel: 32b unsigned channel number. Channel 0 is the emergency
            broadcast that must be decodable by all channels.
        :param frame: Frame to encode. Max frame size is 64 bytes.
        :param timestamp: 64b timestamp to use for encoding. **NOTE**: This value may
            have no relation to the current timestamp, so you should not compare it
            against the current time. The timestamp is guaranteed to strictly
            monotonically increase (always go up) with subsequent calls to encode

        :returns: The encoded frame, which will be sent to the Decoder
        """

        if channel == 0:
            # Channel 0 does not need a subscription, so it is not encrypted using the hash tree.
            message = struct.pack("<IQ", channel, timestamp) + frame
        else:
            seed = bytes.fromhex(self.seeds[str(channel)])

            # Compute this timestamp's encryption key by starting at the top of the tree with the
            # channel's seed value, and going down the tree by taking the left or right hash
            # based on the bits of the timestamp.
            curr = seed
            for i in range(HASH_TREE_HEIGHT, -1, -1):
                if timestamp & (1 << i) == 0:
                    curr = blake3(curr + LEFT_SALT).digest(length=24)
                else:
                    curr = blake3(curr + RIGHT_SALT).digest(length=24)

            # Encrypt the message using the computed key (extended from 24 to 32 bytes).
            # Since each key is only once, it is okay to have an all-zero nonce.
            encrypted_frame = Salsa20.new(key=curr+curr[:8], nonce=bytes([0 for _ in range(8)])).encrypt(frame)

            message = struct.pack("<IQ", channel, timestamp) + encrypted_frame

        # Sign the message using the private key.
        signature = self.signer.sign(message)

        # Encrypt the message again using the metadata key so that the channel, timestamp, and channel 0 frame
        # data are also encrypted. The nonce is the first 8 bytes of the signature since that is a random value
        # which the decoder can know without us including any additional data in our message.
        return signature + Salsa20.new(key=self.metadata_key, nonce=signature[0:8]).encrypt(message)


def main():
    """A test main to one-shot encode a frame

    This function is only for your convenience and will not be used in the final design.

    After pip-installing, you should be able to call this with:
        python3 -m ectf25_design.encoder path/to/test.secrets 1 "frame to encode" 100
    """
    parser = argparse.ArgumentParser(prog="ectf25_design.encoder")
    parser.add_argument(
        "secrets_file", type=argparse.FileType("rb"), help="Path to the secrets file"
    )
    parser.add_argument("channel", type=int, help="Channel to encode for")
    parser.add_argument("frame", help="Contents of the frame")
    parser.add_argument("timestamp", type=int, help="64b timestamp to use")
    args = parser.parse_args()

    encoder = Encoder(args.secrets.read())
    print(repr(encoder.encode(args.channel, args.frame.encode(), args.timestamp)))


if __name__ == "__main__":
    main()
