"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import json
from pathlib import Path
import struct
from dataclasses import dataclass
from loguru import logger
from blake3 import blake3
from Crypto.Cipher import Salsa20
from Crypto.Signature import eddsa
from Crypto.PublicKey import ECC

HASH_TREE_HEIGHT = 64
LEFT_SALT = b"L"
RIGHT_SALT = b"R"


def hash(data: bytes):
    return blake3(data).digest(length=24)


@dataclass(frozen=True)
class Root:
    offset: int
    power: int


def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription.

    The output of this will be passed to the Decoder using ectf25.tv.subscribe

    :param secrets: Contents of the secrets file generated by ectf25_design.gen_secrets
    :param device_id: Device ID of the Decoder
    :param start: First timestamp the subscription is valid for
    :param end: Last timestamp the subscription is valid for
    :param channel: Channel to enable
    """

    secrets = json.loads(secrets)
    seed = bytes.fromhex(secrets["seeds"][str(channel)])
    subscription_salt = bytes.fromhex(secrets["subscription_salt"])
    signer = eddsa.new(ECC.import_key(secrets["private_key"]), "rfc8032")
    subscription_key = blake3(f"{subscription_salt.hex()}{device_id:08x}".encode()).digest()

    roots = get_roots(start, end)

    hashes = []
    for root in roots:
        curr = seed
        for i in range(HASH_TREE_HEIGHT, root.power - 1, -1):
            if root.offset & (1 << i) == 0:
                curr = hash(curr + LEFT_SALT)
            else:
                curr = hash(curr + RIGHT_SALT)
        hashes.append(curr)

    plaintext_body = struct.pack("<QQH", start, end, channel) + b''.join(hashes)
    signature = signer.sign(plaintext_body)
    encrypted_body = Salsa20.new(key=subscription_key, nonce=signature[0:8]).encrypt(plaintext_body)

    return signature + encrypted_body

def ctz(x: int) -> int:
    if x == 0:
        return HASH_TREE_HEIGHT
    return ((x & -x) - 1).bit_count()


def get_roots(a: int, b: int) -> list[Root]:
    if a > b:
        raise ValueError("Invalid range: a > b")

    ranges = []

    while a <= b:
        power = min((b - a + 1).bit_length() - 1, ctz(a))
        ranges.append(Root(power=power, offset=a))
        a += 1 << power

    return ranges


def parse_args():
    """Define and parse the command line arguments

    NOTE: Your design must not change this function
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Force creation of subscription file, overwriting existing file",
    )
    parser.add_argument(
        "secrets_file",
        type=argparse.FileType("rb"),
        help="Path to the secrets file created by ectf25_design.gen_secrets",
    )
    parser.add_argument("subscription_file", type=Path, help="Subscription output")
    parser.add_argument(
        "device_id", type=lambda x: int(x, 0), help="Device ID of the update recipient."
    )
    parser.add_argument(
        "start", type=lambda x: int(x, 0), help="Subscription start timestamp"
    )
    parser.add_argument("end", type=int, help="Subscription end timestamp")
    parser.add_argument("channel", type=int, help="Channel to subscribe to")
    return parser.parse_args()


def main():
    """Main function of gen_subscription

    You will likely not have to change this function
    """
    # Parse the command line arguments
    args = parse_args()

    subscription = gen_subscription(
        args.secrets_file.read(), args.device_id, args.start, args.end, args.channel
    )

    # Print the generated subscription for your own debugging
    # Attackers will NOT have access to the output of this (although they may have
    # subscriptions in certain scenarios), but feel free to remove
    #
    # NOTE: Printing sensitive data is generally not good security practice
    logger.debug(f"Generated subscription: {subscription}")

    # Open the file, erroring if the file exists unless the --force arg is provided
    with open(args.subscription_file, "wb" if args.force else "xb") as f:
        f.write(subscription)

    # For your own debugging. Feel free to remove
    logger.success(f"Wrote subscription to {str(args.subscription_file.absolute())}")


if __name__ == "__main__":
    main()
