#import "@preview/cetz:0.3.2"

#set heading(numbering: "1.")
#set page("us-letter", numbering: "1")

#show link: it => {
  if type(it.dest) == str and it.dest.starts-with("https://") {
    text(underline(it), fill: blue)
  } else {
    it
  }
}

#show ref: it => {
  let target = str(it.target)
  if target.starts-with("sr") {
    let match = target.match(regex("sr(\d)"))
    if it.supplement != auto {
      link(it.element.location(), [*SR#match.captures.at(0)*: #it.supplement])
    } else {
      link(it.element.location(), [*SR#match.captures.at(0)*])
    }
  } else if target.starts-with("as") {
    let match = target.match(regex("as(\d)"))
    if it.supplement != auto {
      link(it.element.location(), [*AS#match.captures.at(0)*: #it.supplement])
    } else {
      link(it.element.location(), [*AS#match.captures.at(0)*])
    }
  } else {
    it
  }
}

#set table(stroke: (_, y) => if y == 0 {
  (bottom: 1pt)
})

#align(center, text(size: 18pt, [OSU Satellite TV for MITRE eCTF 2025]))

#outline(indent: 1em)

#pagebreak()

= Team

The team is comprised of the following people from the Ohio State State University:

#table(
  columns: (1fr, 1fr),
  table.header([*Student*], [*Advisor*]),
  [Christopher Begines], [Julia Armstrong],
  [Mark Bundschuh], [Dr. Felix Engelmann],
  [William Comer], [],
  [Mason Erwine], [],
  [Aditya Gupta], [],
  [Ryan Jackman], [],
  [Cadan Keller], [],
  [Jack Leverett], [],
  [Christopher McDevitt], [],
  [Maxwell McGee], [],
  [Jacob Mcquade], [],
  [Diego Noria], [],
  [Divij Sasidhar], [],
  [Joshua Sims], [],
  [Eva Smith], [],
  [JT Vendetti], [],
  [Matthew Weikel], [],
  [Zihao Zhang], [],
)

= Introduction

This document describes OSU's implementation of a secure satellite TV system as specified by #link("https://rules.ectf.mitre.org/2025", [MITRE's eCTF 2025]). The Satellite TV system features a simulated satellite sending ASCII art to subscribed hardware Decoder devices, implementing the Functional Requirements (@functional-requirements). The decoder devices are #link("https://analog.com/resources/evaluation-hardware-and-software/evaluation-boards-kits/max78000fthr", [MAX78000FTHR microcontrollers by Analog Devices]). The system is secured according to the Security Requirements (@security-requirements), and designed to defend against attacks as outlined in Attack Scenarios (@attack-scenarios), which revolve around erroneously decoding frames sent by a satellite.

// == Source Code and Documentation

// #grid(
//   columns: 2,
//   column-gutter: 2em,
//   row-gutter: 0.75em,
//   [Source Code:],
//   link("https://github.com/OSU-embedded-security-club/ectf-osu-2025")[https://github.com/OSU-embedded-security-club/ectf-osu-2025],

//   [Documentation:],
//   link("https://osu-embedded-security-club.github.io/ectf-osu-2025")[https://osu-embedded-security-club.github.io/ectf-osu-2025],
// )

= Functional Requirements <functional-requirements>

The two main components are the Encoder and Decoder. The encoder receives frames of up to 64 bytes, and converts them into our custom format before sending it over the satellite link. Then, each decoder receives the frame, and must decode the message into the original 64 bytes.

#figure(
  image("2025 eCTF High Level System.png"),
  caption: [Full system with blue highlights indicating components which need to be implemented. @mitreECTF],
)

== Functional Requirement 1: List Channels

#quote([The Decoder must be able to list the channel numbers that the Decoder has a valid subscription for.]) @mitreECTF

== Functional Requirement 2: Update Subscription

#quote([The Decoder must be able to update it’s channel subscriptions with a valid update package. If a subscription update for a channel is received for a channel that already has a subscription, the Decoder must only use the latest subscription update.]) @mitreECTF

== Functional Requirement 3: Decode Frame

#quote([ The Decoder must properly decode TV frame data from any channel that has a valid and active subscription installed or for any emergency broadcast frames.]) @mitreECTF

== Available Channels <available-channels>

A decoder must be able to store up to 8 subscriptions, which must persist over reboots.
Additionally, Channel 0 is reserved as an Emergency Channel which all decoders must be able to decode, as if they always had an active subscription.
The deployment may be provisioned with up to $2^32-1$ channels.

= Security Requirements <security-requirements>

== Security Requirement 1: Active Subscription <sr1>

#quote([An attacker should not be able to decode TV frames without a Decoder that has a valid, active subscription to that channel.]) @mitreECTF

See @encode-decode on how the design protects against the security requirement.

== Security Requirement 2: Authentication <sr2>

#quote([The Decoder should only decode valid TV frames generated by the Satellite System the Decoder was provisioned for.]) @mitreECTF

See @signature on how the design protects against the security requirement.

== Security Requirement 3: Increasing Timestamps <sr3>

#quote([The Decoder should only decode frames with strictly monotonically increasing timestamps.]) @mitreECTF

See @global-timestamp on how the design protects against the security requirement.

= Attack Scenarios <attack-scenarios>

We consider 5 different scenarios where the attackers have access to certain information that the system is designed to protect against.

== Attack Scenario 1: Expired Subscription <as1>

An attacker has physical access to a decoder with a valid subscription to a channel. The timestamp of the current frames sent by the encoder is past the ending timestamp of the attacker's subscription.

See @encode-decode on how the design protects against the attack scenario.

== Attack Scenario 2: Pirated Subscription <as2>

An attacker has physical access to a decoder, and a valid subscription to a channel for a different decoder which they do not have physical access to.

See @subscription on how the design protects against the attack scenario.

== Attack Scenario 3: No Subscription <as3>

An attacker has physical access to a decoder, but has no subscriptions.

See @encode-decode on how the design protects against the attack scenario.

== Attack Scenario 4: Recording Playback <as4>

An attacker has physical access to a decoder, and has been recording the raw data sent by the satellite for some time. Then, they get a valid subscription for the channel. In other words, the attacker should not be able to read past frames given an active subscription.

See @encode-decode on how the design protects against the attack scenario.

== Attack Scenario 5: Pesky Neighbor <as5>

An attacker has physical access to a decoder, and spoofs the satellite signal to a neighbor's decoder which has a valid subscription. The attacker does not have physical access to the neighbor's decoder.

See @signature on how the design protects against the attack scenario.

= Deployment

See the `README.md` at the root of the repository for instructions on setting up dependencies and using the `Taskfile` to execute deployment commands.

== Secrets

The following secrets are generated for a deployment. Once generated, they are global and read only. The deployment secrets are available to the encoder. Some of these secrets will be shared with the Decoders in various forms as described by @decoder.

- $S_1, ..., S_8$
  - Up to 8 32 byte randomly generated seeds, one per encrypted channel
- $S_"subscription"$
  - Randomly generated 64 byte subscription salt
- $K_"secret", K_"public"$
  - An Ed25519 asymmetric key pair
- $K_"metadata"$
  - Randomly generated 32 byte shared symmetric key

== Decoder <decoder>

The firmware must be built for each separate decoder device. When building, specify the `DEVICE_ID` environment variable as a 4 byte hexadecimal number starting with `0x`, denoted as $D_"id"$.

At build time, the decoder derives the following secrets and stores them within the encrypted firmware:

- $K_"metadata"$
  - Shared 32 byte symmetric key with the Encoder which is used to encrypt the metadata (timestamp, channel id) for decode packets
- $K_"public"$
  - Shared public key with the Encoder
- $K_"subscription"$
  - Derived as $"blake3"(S_"subscription"+D_"id")$, and is the symmetric key used to encrypt and decrypt subscriptions for a particular decoder
- $K_"flash"$
  - Randomly generated 32 byte symmetric used to encrypt data before writing it to the flash storage

= System Design

== Encode and Decode <encode-decode>

#let bytesize(bytes) = rect(
  width: 4pt * bytes,
  height: 5pt,
  fill: navy,
  stroke: navy,
)
#let variablebytesize(bytes) = box(
  width: 4pt * bytes,
  repeat(rect(width: 4pt, height: 5pt, stroke: navy)),
)

#figure(
  align(
    center,
    table(
      columns: 3,
      align: left,
      table.header([Field Name], [Size], [Relative Size]),
      [Signature], [64 bytes], bytesize(64),
      [Channel Id], [4 bytes], bytesize(4),
      [Timestamp], [8 bytes], bytesize(8),
      [Message], [up to 64 bytes], variablebytesize(64),
    ),
  ),
  caption: [Structure of a decode packet],
)

Each frame has an integer timestamp $t in [0, 2^64 - 1]$. We derive a unique key $k_t$ for each timestamp which the encoder will use to encrypt the _Message_, and the decoder will use to decrypt the _Message_, both using Salsa20. The keys are derived with a _binary hash key derivation tree_. This ia a binary tree with the channel's seed value, $S_"channel_id"$ at the root. For each node, the left child is \ $L(x)="blake3"(x + #quote(math.upright("L")))$ and the right child is $R(x)="blake3"(x+#quote(math.upright("R")))$. @hash-key-derivation-tree is a diagram of a small hash key derivation tree for $t in [0, 7]$. For example, the key for timestamp 3 is computed using 3 hashes, $k_3 = h_011 = R(R(L(S_"channel_id")))$. Note that the full sized tree has a height of $64$ and $2^64$ leaves, so the encoder can calculate the frame's key with 64 hashes. The encoder encrypts _Message_ with the frame's key with Salsa to form _EncryptedMessage_. Since each key is only used once, this encryption always uses 0 as a nonce.

For channel 0, there are no subscriptions, so this first layer of encryption doesn't occur, and _EncryptedMessage_ = _Message_.

After the _Message_ is encrypted with frame's key, _Channel Id_, _Timestamp_, and _EncryptedMessage_ are signed with $K_"private"$ to form the _Signature_ which is prepended to the data. Then, those three fields are Salsa encrypted with the symmetric $K_"metadata"$ key using the first 8 bytes of _Signature_ as a nonce. The signature is concatenated with the encrypted _Channel Id_, _Timestamp_, and _EncryptedMessage_ to form the final message.

#figure(
  align(
    center,
    scale(
      80%,
      cetz.canvas({
        import cetz.draw: *

        set-style(mark: (fill: black, scale: 1))

        let height = 4
        let xscale = 1.5
        for i in range(height) {
          let y = -(i * 3)
          let ynext = -((i + 1) * 3)
          for j in range(calc.pow(2, i)) {
            let z = calc.pow(2, height - i) / 2
            let h = j * z
            let x = h * xscale
            let xnext = (h + z) * xscale
            let xrightchild = (h + z / 2.1) * xscale
            let color = if (i, j) == (3, 1) or (i, j) == (2, 1) or (i, j) == (
              2,
              2,
            ) {
              red
            } else {
              black
            }
            circle((x, y), radius: .5, stroke: color)
            if i == height - 1 {
              content((x, y), $k_#h$)
            } else {
              let nums = ()
              for I in range(i) {
                let d = calc.rem(
                  calc.floor(h / (calc.pow(2, height - 2 - I))),
                  2,
                )
                nums.push(d)
              }
              content((x, y), $h_#nums.map(x => $#x$).join()$)
            }
            if i != height - 1 {
              line((x + .5, y), (xnext - 1, y), stroke: color)
              line(
                (x, y - .5 - .25),
                (x, ynext + .5 + .25),
                mark: (end: "stealth"),
                name: "l",
              )
              content(
                ("l.start", 50%, "l.end"),
                anchor: "east",
                padding: .25,
              )[L]
              line(
                (x, y - .5 - .25),
                (xrightchild, ynext + .5 + .25),
                mark: (end: "stealth"),
                name: "l",
              )
              content(
                ("l.start", 50%, "l.end"),
                anchor: "west",
                padding: (height - 1 - i) * .25,
              )[R]
            }
          }
        }
      }),
      reflow: true,
    ),
  ),
  caption: [A hash key derivation tree from $t=0$ to $t=7$. The 4 red nodes \ would be sent to the decoder for a subscription from $t = 1$ to $t = 5$.],
) <hash-key-derivation-tree>

To allow the decoder to decrypt frames in its subscription, subscription packets contain nodes from the tree that cover the subscription's range, but not any timestamps outside of the range. These nodes are called "roots". For example, the nodes highlighted in red in @hash-key-derivation-tree are the roots for a subscription from $t = 1$ to $t = 5$. $h_001 => { k_1 }$, $h_01 => { k_2, k_3 }$, and $h_10 => { k_4, k_5 }$, so only $h_001$, $h_01$, and $h_10$ are needed to form the subscription. To decode a frame inside the subscription, the decoder computes only the hashes required to go from a root to a leaf node, then uses that result to decrypt the frame data.

This aspect of the design secures the system in the following ways:

- @sr1[Active Subscription]
  - The decoder is never given more keys than exactly those which correspond to the timestamps in the subscription it was given. This means it is cryptographically impossible to decrypt frames outside of the subscription interval.
- @as1[Expired Subscription]
  - The decoder is never given keys for the frames past the end of the subscription interval, so it is cryptographically impossible to decrypt frame data past the end of its subscription.
- @as3[No Subscription]
  - Attackers without any subscription have no keys for any frames, so they are unable to decode any frames at all.
- @as4[Recording Playback]
  - The decoder is never given keys for the frames outside of the subscription interval, so it is not possible to decrypt past frames.

== Subscription <subscription>

#figure(
  align(
    center,
    table(
      columns: 3,
      align: left,
      table.header([Field Name], [Size], [Relative Size]),
      [Signature], [64 bytes], bytesize(64),
      [Start Timestamp], [8 bytes], bytesize(8),
      [End Timestamp], [8 bytes], bytesize(8),
      [Channel Id], [4 bytes], bytesize(4),
      [Root Hashes],
      ${24n "bytes" | n <= 126 }$,
      box(box(bytesize(24)) + " " + box($...n "times"$)),
    ),
  ),
  caption: [Structure of a subscribe packet],
)

To generate a subscription, the encoder calculates the root hashes to send to the decoder that will allow it to decode only frames in the timestamp.
The locations of the roots are computed using the algorithm described in @algorithm.
A root location is defined by its offset (starting timestamp) and its power (how high it is in the tree).
Its length is $2^"power"$.
Then the encoder calculates the hashes for each root, starting at the root node and going down to the root's power, doing left or right hashes based on the bits of the roots's offset.

The plaintext contents _Start Timestamp_, _End Timestamp_, _Channel Id_, and _Root Hashes_ are signed with $K_"private"$ to form the _Signature_ which is prepended to the data. Then, those four fields are encrypted with $K_"subscription"$ using the first 8 bytes of _Signature_ as a nonce, which forms the final subscribe packet. This ensures that subscriptions can only be used by the decoder for which the subscription was generated.

The decoder runs the same algorithm as the encoder to locate the root nodes from the start and end timestamps, so the subscription packet can contain only the hash values, with no extra metadata like root locations or number of roots.
The proof in @proof shows that this scheme requires no more than 126 root nodes.
See @algorithm for the algorithm which is used to find the root nodes corresponding to a timestamp range.

Unlike in @encode-decode, the _Channel Id_ may not be 0, because every decoder is assumed to already be subscribed to Channel 0 (the Emergency Channel).

This aspect of the design secures the system in the following ways:

- @as2[Pirated Subscription]
  - Encrypting the subscription file with $K_"subscription"$ means that an attacker needs physical access to the decoder which a subscription was generated for. Additionally, signing the subscription with asymmetric cryptography ensures that further subscriptions are created by the encoder and cannot be forged by other decoders. In the Pirated Subscription scenario, the attacker is given a subscription file for a device id which they do not have, so it is not possible to extract the key and decrypt the subscription to apply it to the attacker's own decoder.

== Signatures <signature>

The encoder uses the secret key $S K$ to sign every message with a 64 byte Ed25519 signature. The public key $P K$ is stored within all decoders as a static variable in the `.rodata` section and verifies every message to ensure it came from the encoder it was provisioned with.

This aspect of the design secures the system in the following ways:

- @sr2[Authentication]
  - Using asymmetric cryptographic, the decoder can ensure that it only accepts messages from the encoder it was provisioned with. Additionally, it prevents a compromised decoder from sending messages to other decoders, unlike symmetric cryptography.
- @as5[Pesky Neighbor]
  - Bypassing the signature would require an attacker to write their own public key into the decoder which they want to receive messages on. In the Pesky Neighbor attack scenario, attackers do not have physical access to the neighbor's decoder, meaning that no side channel or other embedded attacks are possible. Additionally, using Zig, we can have memory safety guarantees which prevent memory vulnerabilities required to write to overwrite the neighbor's public key.

== Global Timestamp <global-timestamp>

A global timestamp is kept in the RAM of the decoder, and is used to reject misordered frames. It increases on every successful decode.

This aspect of the design secures the system in the following ways:

- @sr3[Increasing Timestamps]
  - The timestamp can be checked against the timestamp in the frame before attempting to decode the data in frame, ensuring that the decoder never decodes an earlier frame.

== Memory Protection Unit

The Memory Protection Unit (MPU) is enabled on the decoder as a defensive countermeasure to code injection and serves as an additional layer of security. We disable writing to flash, and prevent executing in SRAM.

== Encryption at Rest

Before writing to flash, the contents of the page are first encrypted with a symmetric key $K_"flash"$ using Salsa20. $K_"flash"$ created by the decoder at build time and stored within the encrypted firmware (see @decoder). An incrementing nonce is stored next to each page in plaintext, to prevent nonce reuse. This adds another layer of security aiming to prevent offline attacks where a sophisticated attacker is able to dump the flash of the decoder and brute force the subscription's root hashes.

== Zig

The #link("https://ziglang.org", [Zig programming language]) was selected as the language to write the secure decoder in. Zig has memory safety features like protection from indexing an array out of bounds, double free protections and more. Additionally, it includes a comprehensive standard library which securely implements many cryptographic functions, among many other quality of life functions. Most importantly, Zig can do all this while maintaining perfect C compatibility and using the MSDK provided by Analog Devices Inc (the developer of the MAX78000FTHR), without requiring a rewrite of the Hardware Abstraction Layer (HAL). This allowed the team to move incredibly quickly while ensuring a high level of security.

= Appendix

== Proof that any interval can be encoded with at most 126 roots <proof>

By the Theorem (@theorem) proved below, any interval $[a, b]$ can be encoded by at most $2n-2$ roots. Timestamps are $64$ bit unsigned integers, so we choose $n=64$. Therefore, no more than $2(64)-2=126$ roots are required to encode any interval on $[0, 2^64-1]$.

=== Definitions

We will start by making a few mathematical definitions for the concepts of roots and trees.

A _root_, which is the location of a node in the hash key derivation tree, is a tuple $(o, l)$ where $l$ is a power of 2 and $o$ is a multiple of $l$. Its _power_ is $log_2(l)$. (If $o$ is 0, $l$ can be any positive power of 2).


A root $(o, l)$ _contains_ a timestamp $x$ if $o <= x <= o+l - 1$.

A _tree_ is a finite set of roots (these would sent in a subscription packet to the decoder).

To say that an interval $I$ can be _encoded by_ a tree $T$ is to say that $union.big_((o, l) in T) [o, o+ l - 1]=I$.

We will prove that any interval in a tree of height $n$ can be encoded by a tree with at mosts $2n - 2$ roots.

=== Lemma 1 <lemma1>

For all $n >= 1$, any interval $[0, k]$, where $k <= 2^n-1$, can be encoded by a tree containing at most $n$ roots.

*Base case*, $n=1$:

We want to show that any interval $[0, k]$ where $k <= 2^1 - 1 = 1$ can be encoded by at most 1 root.

- ${(0, 1)}$ encodes $[0, 0]$
- ${(0, 2)}$ encodes $[0, 1]$

*Induction hypothesis:* Suppose any interval $[0, k]$ where $k <= 2^n-1$ can be encoded by a tree with at most $n$ roots.

We wish to show that any interval on $[0, b]$ where $b <= 2^(n+1)-1$ can be encoded by a tree with at most $n+1$ roots.

Let $I = [0, b]$ where $b <= 2^(n+1)-1$.

*Case 1:* $b < 2^n$: By the induction hypothesis, $I$ can be encoded with a tree with at most $n <= n + 1$ roots.

*Case 2:* $2^n <= b < 2^(n+1)$: Then $I = [0, 2^n - 1] union [2^n, b]$.

The first interval, $[0, 2^n - 1]$ can be encoded by $1$ root, namely, $(0, 2^n)$.

Since $b-2^n < 2^n$, we can shift the second interval $[2^n, b]$ to the left by $2^n$, obtaining the interval $[0, b - 2^n]$, which by the induction hypothesis can be encoded by a tree $T$ containing at most $n$ roots.

Shifting that tree back to the right, we obtain $T' = {(o + 2^n, l) | (o, l) in T}$ which encodes $[2^n, b]$. $T'$ has the same number of roots as $T$, so $T'$ has at most $n$ roots.

Therefore, $I$ is encoded by ${(0, 2^n)} union T'$, which contains at most $n+1$ roots.

=== Lemma 2 <lemma2>

For all $n >= 1$, any interval $[k, 2^n-1]$ can be encoded with at most $n$ roots.

Let $T$ be the tree which by Lemma 1 encodes $[0, 2^n-1-k]$ and contains at most $n$ roots.
Then let $T' = {(2^n-l-o,l) | (o, l) in T}$, which also contains at most $n$ roots.
Intuitively, this is the tree $T$ flipped horizontally.

We will show that $T'$ encodes $[k, 2^n-1]$ by considering an arbitrary timestamp $x in [k, 2^n - 1]$. \
$2^n-1-x$ is within the interval $[0,k]$, so there exists a root $(o, l) in T$ which contains $2^n-1-x$, that is, $o <= 2^n-1-x <= o + l$.
Therefore, $2^n - 1 - l - o <= x <= (2^n - 1 - l - o) + l$, so the corresponding root in $T'$, $(2^n-l-o,l)$, contains $x$.

=== Theorem <theorem>

For all $n >= 2$, any interval on $[0, 2^n - 1]$ can be encoded by at most $2n-2$ roots.

*Base case*, $n=2$:

We want to show that all intervals on $[0, 3]$ can be encoded by at most $2$ roots.

- ${(x, 1)}$ encodes $[x, x]$ for $x in [0, 3]$
- ${(0, 2)}$ encodes $[0, 1]$
- ${(0, 2), (2, 1)}$ encodes $[0, 2]$
- ${(0, 4)}$ encodes $[0, 3]$
- ${(1, 1), (2, 1)}$ encodes $[1, 2]$
- ${(1, 1), (2, 2)}$ encodes $[1, 3]$
- ${(2, 1), (3, 1)}$ encodes $[2, 3]$

*Induction hypothesis*: Suppose any interval on $[0, 2^n - 1]$ can be encoded by at most \ $2n-2$ roots.

We wish to show that any interval on $[0, 2^(n+1)-1]$ can be encoded by at most $2(n+1)-2=2n$ roots.

Let $I = [a, b]$ be a interval on $[0, 2^(n+1) -1]$.

*Case 1*: $a <= b < 2^n$. Intuitively, this means the range is within the left half of the tree. By the induction hypothesis, $I$ can be encoded by $2n-2 <= 2n$ roots.

*Case 2*: $2^n <= a <= b$. Intuitively, this means the range is within the right half of the tree.
\ The interval $[a - 2^n, b-2^n]$ is a subinterval of $[0, 2^n-1]$, so by the induction hypothesis, there is a tree $T$ containing at most $2n-2$ roots which encodes $[a - 2^n, b-2^n]$.
Thus, the tree \ $T' = {(o+2^n, l) | (o,l) in T}$, also containing at most $2n-2$ roots, encodes $[a, b]$.

*Case 3*: $a < 2^n <= b$. Intuitively, this means the interval crosses the center of the tree. \ So $I=[a, 2^n - 1] union [2^n, b]$.
By #link(<lemma2>, [Lemma 2]), $[a, 2^n - 1]$ can be encoded by a tree $T$ containing most $n$ roots.
Similarly, by #link(<lemma1>, [Lemma 1]), $[0, b-2^n]$ can be encoded by can be encoded by a tree $S$ containing at most $n$ roots, so $S' = {(o + 2^n, l) | (o, l) in S}$ encodes $[2^n, b]$.
Therefore, $I$ can be encoded by $T union S'$, which contains at most $n + n = 2n$ roots.

== Algorithm to calculate root node positions in the hash key derivation tree <algorithm>

#let style-number(number) = text(gray)[#number]
#show raw.where(block: true): it => grid(
  columns: 2,
  align: (right, left),
  gutter: 0.5em,
  ..it.lines.enumerate().map(((i, line)) => (
    style-number(i + 1),
    line,
  )).flatten()
)
This algorithm computes the positions of the smallest set of nodes in the hash tree that allows the computation of all keys
within the range of timestamps $[a, b]$ (inclusive), but none outside of that range.
The same algorithm is implemented in the subscription generator in Python and on the decoder in Zig.
It works by repeatedly adding the highest possible root that doesn't go too long while iterating over the range from left to right.
The length of a node must be a power of 2 multiple of its offset, which is why the power is limited
by the number of trailing zeroes of the offset.
We also make sure that the power does not go to long, by ensuring that the starting location plus the length is not larger than
the ending timestamp.

```py
class Root:
    """
    The position of a node in the hash key derivation tree.

    Offset is the starting timestamp of the node.
    Power is its position vertically. A power of 0 means a node at the bottom of a
    tree (representing an individual timestamp's key), and a power of 64 is at
    the top (representing the entire range of timestamps).

    A node's offset is always a multiple of 2**power.

    Knowing the value of a hash at a root allows one to compute timestamps
    in the range [offset, offset+2**power - 1] (inclusive).
    """
    offset: int
    power: int


def get_roots(a: int, b: int) -> list[Root]:
    if a > b:
        raise ValueError("Invalid range: a > b")

    ranges = []

    while a <= b:
        # `ctz(a)` (count trailing zeroes) is the largest
        # that the power can be due to the alignment of `a`.
        # Also, we need `a + 2**power - 1 <= b` so the range doesn't go too long,
        # which implies `power <= (b - a + 1).bit_length() - 1`.
        power = min((b - a + 1).bit_length() - 1, ctz(a))
        ranges.append(Root(power=power, offset=a))
        a += 2 ** power

    return ranges
```

#bibliography("citations.bib")
