#import "@preview/cetz:0.3.2"

#set heading(numbering: "1.")
#set page("us-letter", numbering: "1")

#show ref: it => {
  let target = str(it.target)
  if target.starts-with("sr") {
    let match = target.match(regex("sr(\d)"))
    if it.supplement != auto {
      link(it.element.location(), [*SR#match.captures.at(0)*: #it.supplement])
    } else {
      link(it.element.location(), [*SR#match.captures.at(0)*])
    }
  } else if target.starts-with("as") {
    let match = target.match(regex("as(\d)"))
    if it.supplement != auto {
      link(it.element.location(), [*AS#match.captures.at(0)*: #it.supplement])
    } else {
      link(it.element.location(), [*AS#match.captures.at(0)*])
    }
  } else {
    it
  }
}

#set table(stroke: (_, y) => if y == 0 {
  (bottom: 1pt)
})

#align(center, text(size: 18pt, [OSU Satellite TV for MITRE eCTF 2025]))

#outline(indent: 1em)

#pagebreak()

= Team

The team is comprised of the following people from the Ohio State State University:

#table(
  columns: (1fr, 1fr),
  table.header([*Student*], [*Advisor*]),
  [Christopher Begines], [Julia Armstrong],
  [Mark Bundschuh], [Dr. Felix Engelmann],
  [William Comer], [],
  [Mason Erwine], [],
  [Aditya Gupta], [],
  [Ryan Jackman], [],
  [Cadan Keller], [],
  [Jack Leverett], [],
  [Christopher McDevitt], [],
  [Maxwell McGee], [],
  [Jacob Mcquade], [],
  [Diego Noria], [],
  [Divij Sasidhar], [],
  [Joshua Sims], [],
  [Eva Smith], [],
  [Matthew Weikel], [],
  [Zihao Zhang], [],
)

= Introduction

This document describes OSU's implementation of a secure satellite TV system as specified by #link("https://rules.ectf.mitre.org/2025", [MITRE's eCTF 2025]). The Satellite TV system features a simulated satellite sending ASCII art to subscribed hardware Decoder devices, implementing @functional-requirements[Functional Requirements]. The decoder devices are #link("https://analog.com/resources/evaluation-hardware-and-software/evaluation-boards-kits/max78000fthr", [MAX78000FTHR microcontrollers by Analog Devices]). The system is secured according to the @security-requirements[Security Requirements], and designed to defend against attacks as outlined in @attack-scenarios[Attack Scenarios], which revolve around erroneously decoding frames sent by a satellite.

== Functional Requirements <functional-requirements>

The two main components are the Encoder and Decoder. The encoder receives frames of up to 64 bytes, and converts them into our custom format before sending it over the satellite link. Then, each decoder receives the frame, and must decode the message into the original 64 bytes.

#figure(
  image("2025 eCTF High Level System.png"),
  caption: [Full system with blue highlights indicating components which need to be implemented. @mitreECTF],
)

=== Functional Requirement 1: List Channels

#quote([The Decoder must be able to list the channel numbers that the Decoder has a valid subscription for.]) @mitreECTF

=== Functional Requirement 2: Update Subscription

#quote([The Decoder must be able to update it’s channel subscriptions with a valid update package. If a subscription update for a channel is received for a channel that already has a subscription, the Decoder must only use the latest subscription update.]) @mitreECTF

=== Functional Requirement 3: Decode Frame

#quote([ The Decoder must properly decode TV frame data from any channel that has a valid and active subscription installed or for any emergency broadcast frames.]) @mitreECTF

== Security Requirements <security-requirements>

=== Security Requirement 1: Active Subscription <sr1>

#quote([An attacker should not be able to decode TV frames without a Decoder that has a valid, active subscription to that channel.]) @mitreECTF

See @encode-decode on how the design protects against the security requirement.

=== Security Requirement 2: Authentication <sr2>

#quote([The Decoder should only decode valid TV frames generated by the Satellite System the Decoder was provisioned for.]) @mitreECTF

See @signature on how the design protects against the security requirement.

=== Security Requirement 3: Increasing Timestamps <sr3>

#quote([The Decoder should only decode frames with strictly monotonically increasing timestamps.]) @mitreECTF

See @global-timestamp on how the design protects against the security requirement.

== Attack Scenarios <attack-scenarios>

We consider 5 different scenarios where the attackers have access to certain information that the system is designed to protect against.

=== Attack Scenario 1: Expired Subscription <as1>

An attacker has physical access to a decoder with a valid subscription to a channel. The timestamp of the current frames sent by the encoder is past the ending timestamp of the attacker's subscription.

See @encode-decode on how the design protects against the attack scenario.

=== Attack Scenario 2: Pirated Subscription <as2>

An attacker has physical access to a decoder, and a valid subscription to a channel for a different decoder which they do not have physical access to.

See @subscription on how the design protects against the attack scenario.

=== Attack Scenario 3: No Subscription <as3>

An attacker has physical access to a decoder, but has no subscriptions.

See @encode-decode on how the design protects against the attack scenario.

=== Attack Scenario 4: Recording Playback <as4>

An attacker has physical access to a decoder, and has been recording the raw data sent by the satellite for some time. Then, they get a valid subscription for the channel. In other words, the attacker should not be able to read past frames given an active subscription.

See @encode-decode on how the design protects against the attack scenario.

=== Attack Scenario 5: Pesky Neighbor <as5>

An attacker has physical access to a decoder, and spoofs the satellite signal to a neighbor's decoder which has a valid subscription. The attacker does not have physical access to the neighbor's decoder.

See @signature on how the design protects against the attack scenario.

= Deployment

== Secrets

The following secrets are generated for a deployment. Once generated, they are global and read only. The deployment secrets are available to the encoder.

- A 32 byte seed per encrypted channel $S_"channel_id"$
- A 64 byte subscription salt, $S_"subscription"$
- An Ed25519 asymmetric key pair, secret key $S K$ and public key $P K$

== Decoder

The firmware must be built for each separate decoder device. When building, specify the `DEVICE_ID` environment variable as a 4 byte hexadecimal number starting with `0x`.

= System Design

== Encode and Decode <encode-decode>

#let bytesize(bytes) = rect(width: 4pt * bytes, height: 5pt, fill: navy)

#align(
  center,
  table(
    columns: 3,
    align: left,
    table.header([Field Name], [Size], [Relative Size]),
    [Channel ID], [1 byte], bytesize(1),
    [Timestamp], [8 bytes], bytesize(8),
    [Message], [64 bytes], bytesize(64),
    [Signature], [64 bytes], bytesize(64),
  ),
)

Each frame has an integer timestamp $t in [0, 2^64 - 1]$. Each timestamp has a unique symmetric key $k_t$ which the encoder will use to encrypt the message, and the decoder will use to decrypt the message, both using Salsa20. The keys are derived with a _binary hash key derivation tree_. Let $H$ be a cryptographic hash function. We have chosen $H="blake3"$. Let $L$ and $R$ be salted hash functions $L(x)=H(x + \""left"\")$ and $R(x)=H(x+\""right"\")$. The encoder uses secret $S_"channel_id"$ for the channel id currently being broadcasted, and generates a root hash $h=H(S)$. Then, two hashes $h_0=L(h)$ and $h_1=L(h)$ are derived. Then $h_00=L(h_0)$, $h_01=R(h_0)$, $h_10=L(h_1)$, and $h_11=R(h_1)$, and so on. This process continues to form a tree of height $64$. The leaves of the tree form the keys $k_t$, one for every timestamp. @hash-key-derivation-tree shows a hash key derivation tree for $t in [0, 7]$ and has $8$ leaves. Note that the full sized tree has $2^64$ leaves, the leaves are computed on demand for particular timestamps since it would be computationally infeasible to precompute all keys for such a large tree.

#figure(
  align(
    center,
    cetz.canvas({
      import cetz.draw: *

      set-style(mark: (fill: black, scale: 1))

      let height = 4
      let xscale = 1.5
      for i in range(height) {
        let y = -(i * 3)
        let ynext = -((i + 1) * 3)
        for j in range(calc.pow(2, i)) {
          let z = calc.pow(2, height - i) / 2
          let h = j * z
          let x = h * xscale
          let xnext = (h + z) * xscale
          let xrightchild = (h + z / 2.1) * xscale
          circle((x, y), radius: .5)
          if i == height - 1 {
            content((x, y), $k_#h$)
          } else {
            let nums = ()
            for I in range(i) {
              let d = calc.rem(calc.floor(h / (calc.pow(2, height - 2 - I))), 2)
              nums.push(d)
            }
            content((x, y), $h_#nums.map(x => $#x$).join()$)
          }
          if i != height - 1 {
            line((x + .5, y), (xnext - 1, y))
            line(
              (x, y - .5 - .25),
              (x, ynext + .5 + .25),
              mark: (end: "stealth"),
              name: "l",
            )
            content(("l.start", 50%, "l.end"), anchor: "east", padding: .25)[L]
            line(
              (x, y - .5 - .25),
              (xrightchild, ynext + .5 + .25),
              mark: (end: "stealth"),
              name: "l",
            )
            content(
              ("l.start", 50%, "l.end"),
              anchor: "west",
              padding: (height - 1 - i) * .25,
            )[R]
          }
        }
      }
    }),
  ),
  caption: [A hash key derivation tree from $t=0$ to $t=7$],
) <hash-key-derivation-tree>

To send the keys to the decoder, they are compressed into a subscription file. The compression is done by finding the largest power of two intervals which span the entire interval of timestamps $t in ["start", "end"]$. For example, all keys in $[1, 5]$ can be derived by $h_001 => { k_1 }$, $h_01 => { k_2, k_3 }$, and $h_10 => { k_4, k_5 }$, so only $h_001$, $h_01$, and $h_10$ are needed to form a subscription. The worst case interval is $[1, 2^64-2]$ which requires $126$ subtree roots.

- @sr1[Active Subscription]
  - The decoder is never given more keys than exactly those which correspond to the timestamps in the subscription it was given. This means it is cryptographically impossible to decrypt frames outside of the subscription interval.
- @as1[Expired Subscription]
  - The decoder is never given keys for the frames past the end of the subscription interval, so it is cryptographically impossible to decrypt frame data past the end of its subscription.
- @as3[No Subscription]
  - Attackers without any subscription have no keys for any frames, so they are unable to decode any frames at all.
- @as4[Recording Playback]
  - The decoder is never given keys for the frames outside of the subscription interval, so it is not possible to decrypt past frames.

== Subscription <subscription>

#align(
  center,
  table(
    columns: 3,
    align: left,
    table.header([Field Name], [Size], [Relative Size]),
    [Channel ID], [1 byte], bytesize(1),
    [Start Timestamp], [8 bytes], bytesize(8),
    [End Timestamp], [8 bytes], bytesize(8),
    [Packed Subtree Root Hashes],
    ${24n "bytes" | n in NN^+ and n <= 126 }$,
    box(box(bytesize(24)) + " " + box($...n "times"$)),
  ),
)

The decoder runs the same algorithm using the start and end timestamps as the encoder to figure out where the subtree root hashes are, so no extra metadata is required to positions the hashes, or to know how many there are.

#let ksub = $k_"subscription"$

The entire subscription payload is symmetricly encrypted using Salsa20 with a key $#ksub =H(S + "DEVICE_ID")$. #ksub is stored within the decoder as a static variable in the `.rodata` section when it is provisioned and can be used to decrypt a subscription. This ensures that subscriptions can only be used by the decoder the subscription was generated for.

This design ensures against the following:

- @as2[Pirated Subscription]
  - Encrypting the subscription file with #ksub means that an attacker needs physical access to the decoder which a subscription was generated for. In the Pirated Subscription scenario, the attacker is given a subscription file for a device id which they do not have, so it is not possible to extract the key and decrypt the subscription to apply it to the attacker's own decoder.

== Signatures <signature>

The encoder uses the secret key $S K$ to sign every message with a 64 byte Ed25519 signature. The public key $P K$ is stored within all decoders as a static variable in the `.rodata` section and verifies every message to ensure it came from the encoder it was provisioned with.

- @sr2[Authentication]
  - Using asymmetric cryptographic, the decoder can ensure that it only accepts messages from the encoder it was provisioned with. Additionally, it prevents a compromised decoder from sending messages to other decoders, unlike symmetric cryptography.
- @as5[Pesky Neighbor]
  - Bypassing the signature would require an attacker to write their own public key into the decoder which they want to receive messages on. In the Pesky Neighbor attack scenario, attackers do not have physical access to the neighbor's decoder, meaning that no side channel or other embedded attacks are possible. Additionally, using Zig, we can have memory safety guarantees which prevent memory vulnerabilities required to write to overwrite the neighbor's public key.

== Global Timestamp <global-timestamp>

A global timestamp is kept in the RAM of the decoder, and is used to reject misordered frames. It increases on every successful decode.

- @sr3[Increasing Timestamps]
  - The timestamp can be checked against the timestamp in the frame before attempting to decode the data in frame, ensuring that the decoder never decodes an earlier frame.

== Zig

The #link("https://ziglang.org", [Zig programming language]) was selected as the language to write the secure decoder in. Zig has memory safety features like protection from indexing an array out of bounds, double free protections and more. Additionally, it includes a comprehensive standard library which securely implements many cryptographic functions, among many other quality of life functions. Most importantly, Zig can do all this while maintaining perfect C compatibility and using the MSDK provided by Analog Devices Inc (the developer of the MAX78000FTHR), without requiring a rewrite of the Hardware Abstraction Layer (HAL). This allowed the team to move incredibly quickly while ensuring a high level of security.

= Appendix

== Proof that there are no more than 126 nodes

=== Definitions

For a given $n$, a _node_ has an offset $o$ where $o in NN$ and $0 <= o <= 2^n - 1$, and a length $l in {2^x | x in NN and 0 <= x <= n}$.

To say that an interval $I$ can be _encoded by_ $n$ nodes is to say that, $union.big_i^n [o_i, o_i + l_i - 1]=I$.

Two intervals, $I_1=[o_1, o_1 + l_1 - 1]$, and $I_2 = [o_2, o_2 + l_2 - 1]$ are _analogous_ if $l_1=l_2$ and $o_1 mod l_1 = o_2 mod l_2$.

=== Lemma 1 <lemma1>

Any interval on $[0, 2^n-1]$ where $n in NN, n >= 1$ and starting at $0$ can be encoded with at most $n$ nodes.

Base Case, $n=1$:

Let $I$ be an interval on $[0, 2^1 - 1] = [0,1]$ starting at $0$. For $I=[0, 0]$, this can be covered by a $1$ length node at offset 0. For $I=[0, 1]$, this can be covered by a $2$ length node at offset 0.

Induction Hypothesis: Any interval on $[0, 2^n - 1]$ and starting at $0$ can be encoded with at most $n$ nodes.

We wish to show that any interval on $[0, 2^(n+1)-1]$ and starting at $0$ can be encoded with at most $n+1$ nodes.

Let $I$ be an interval in $[0, 2^(n+1)-1]$ starting at $0$, i.e. $I=[0, k]$ where $k<2^(n+1)$.

Case 1: $k < 2^n$: By the induction hypothesis, $I$ can be covered by $n<=n+1$ nodes.

Case 2: $k >= 2^n$: Then $I = [0, 2^n - 1] union [2^n, k]$. The interval $[0, 2^n - 1]$ can be covered by $1$ node, because it is half of the total interval. $[2^n, k]$ is analogous to $[0, 2^n - 1]$. By the induction hypothesis, $[0, 2^n - 1]$ can be covered by at most $n$ nodes. Therefore, $[2^n, k]$ can be covered by at most $n$ nodes. Therefore, $I$ can be covered by at most $n+1$ nodes.

=== Lemma 2 <lemma2>

Any interval on $[k, 2^n-1]$ where $n in NN, n >= 1$ and starting at $k$ can be encoded with at most $n$ nodes.

This follows from Lemma 1, because the interval $[k, 2^n-1]$ is analogous to $[0, 2^n - 1]$.

=== Theorem <theorem>

Any interval on $[0, 2^n - 1]$ where $n in NN, n >= 2$ can be covered by at most $2n-2$ nodes.

Base Case, $n=2$:

Let $I$ be an interval on $[0, 2^2-1]=[0,3]$.

Induction Hypothesis: Any interval on $[0, 2^n - 1]$ where $n in NN, n >= 2$ can be covered by at most $2n-2$ nodes.

We wish to show that any interval on $[0, 2^(n+1)-1]$ where $n in NN, n+1 >= 2 => n>=1$ can be covered by at most $2(n+1)-1=2n$ nodes.

Let $I$ be an interval on $[0, 2^(n+1) -1]$.

Case 1: $I subset [0, 2^n - 1]$. Intuitively, this is within the left half of the interval. By the induction hypothesis, $I$ can be covered by $2n-2 <= 2n$ nodes.

Case 2: $I subset [2^n, 2^(n+1)-1]$. Intuitively, this is within the right half of the interval. The interval $[2^n, 2^(n+1)-1]$ is analogous to the interval $[0, 2^n - 1]$. By the induction hypothesis, $[0, 2^n - 1]$ can be covered by $2n-2$ nodes. Therefore, $I$ can be covered by $2n-2 <= 2n$ nodes.

Case 3: $k < 2^n < l$. Intuitively, this means the interval crosses the middle boundary. Then, $I=[k, 2^n - 1] union [2^n, l]$. By @lemma2[Lemma 2:], $[k, 2^n - 1]$ can be covered by at most $n$ nodes. Similarly, $[2^n, l]$ is analogous to $[0, l-2^n]$, which, by @lemma1[Lemma 1:], can be covered by at most $n$ nodes. Therefore, $I$ can be covered by $n+n=2n$ nodes.

=== Application

Timestamps are $64$ bit unsigned integers, so we choose $n=64$. @theorem[Theorem] shows that no more than $2(64)-2=126$ nodes are required to encode any interval from $[0, 2^64-1]$.

== Proof of node partitioning optimality

We will show that the following algorithm correctly produces the optimal set of nodes to cover an interval $[a, b]$.

#let style-number(number) = text(gray)[#number]
#show raw.where(block: true): it => grid(
  columns: 2,
  align: (right, left),
  gutter: 0.5em,
  ..it.lines.enumerate().map(((i, line)) => (
    style-number(i + 1),
    line,
  )).flatten()
)

```py
class Node:
    offset: int
    power: int

def get_nodes(a: int, b: int) -> list[Node]:
    nodes = []

    while a <= b:
        power = min((b - a + 1).bit_length() - 1, ctz(a))
        ranges.append(Node(offset=a, power=power))
        a += 2 ** power

    return ranges
```

=== Correctness

=== Optimality

#bibliography("citations.bib")
