name: Documentation
on:
  pull_request:
  workflow_dispatch:
  push:
    paths:
      - docs

jobs:
  docs:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install typstyle
      working-directory: docs
      run: |
        wget https://github.com/Enter-tainer/typstyle/releases/download/v0.12.1/typstyle-x86_64-unknown-linux-gnu
        mv typstyle-x86_64-unknown-linux-gnu typstyle
        chmod +x typstyle

    - name: Check formatting
      working-directory: docs
      run: ./typstyle --check design.typ
