name: eCTF
on:
  pull_request:
  push:
jobs:
  ap:
    name: Build AP firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27

    - name: Set up environment
      run: nix-shell --run 'poetry install'

    - name: Compile firmware
      run: ./compile_ap.sh

  comp:
    name: Build Component firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27

    - name: Set up environment
      run: nix-shell --run 'poetry install'

    - name: Compile firmware
      run: ./compile_comp.sh
  
