name: Zig
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install zig
      run: |
        curl -sSfL https://ziglang.org/download/0.13.0/zig-linux-x86-0.13.0.tar.xz | tar -xJ
        echo $PWD/zig-linux-x86-0.13.0 >> $GITHUB_PATH

    - name: Format
      run: zig fmt --check .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install zig
      run: |
        curl -sSfL https://ziglang.org/download/0.13.0/zig-linux-x86-0.13.0.tar.xz | tar -xJ
        echo $PWD/zig-linux-x86-0.13.0 >> $GITHUB_PATH

    - name: Install msdk
      run: |
        git clone --depth=1 --branch v2023_06 https://github.com/Analog-Devices-MSDK/msdk
        echo "MAXIM_PATH=$PWD/msdk" >> $GITHUB_ENV

    - name: Install ARM GCC
      run: |
        sudo apt-get install -y gcc-arm-none-eabi
        echo "GCC_ARM_EMBDEDDED=/usr/lib" >> $GITHUB_ENV

    - name: Run tests
      run: zig build test --summary all

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Install zig
      run: |
        curl -sSfL https://ziglang.org/download/0.13.0/zig-linux-x86-0.13.0.tar.xz | tar -xJ
        echo $PWD/zig-linux-x86-0.13.0 >> $GITHUB_PATH

    - name: Install msdk
      run: |
        git clone --depth=1 --branch v2023_06 https://github.com/Analog-Devices-MSDK/msdk
        echo "MAXIM_PATH=$PWD/msdk" >> $GITHUB_ENV

    - name: Install ARM GCC
      run: |
        sudo apt-get install -y gcc-arm-none-eabi
        echo "GCC_ARM_EMBDEDDED=/usr/lib" >> $GITHUB_ENV

    - name: Build documentation
      run: zig build docs

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

  deploy:
    name: Deploy Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
